services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    ports:
      - 3000:3000
    # env_file:
    #   - .env
    volumes:
      - ./.env:/app/.env
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/.next
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=miniosecret
      - S3_BUCKET_NAME=s3bucket
      # For example, if you want to use Google OAuth API keys, you can store them in
      # the .env file and add the following variables:
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore: 
          - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - db
      - minio
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
volumes:
  postgres-data:
  minio_storage: 
networks:
  anket-bteg: