version: "4"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - "8001:5432"
  web:
    build: .
volumes:
  postgres-data:
