import type { Metadata } from "next";

import { findUsers, removeUser } from "@/actions/users";

import UserList from "@/components/user/UserList";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by trupletj",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const users = await findUsers({
    where: {
      OR: [{ role: { equals: "USER" } }, { role: { equals: "GUEST" } }],
    },
  });

  return (
    <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8 ml-14">
      <div className="grid gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3 max-w-[900px]">
        <UserList users={users} />
        {children}
      </div>
    </main>
  );
}
