import type { Metadata } from "next";

import Aside from "@/components/dashboard/Aside";
import Header2 from "@/components/dashboard/Header";
import SideMenu from "@/components/dashboard/SideMenu";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by trupletj",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Aside />
      <div className="w-full min-h-screen bg-muted/40  ">
        <Header2 />
        {children}
      </div>
    </>
  );
}
