import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Anket",
  description: "Generated by trupletj",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="container py-20">{children}</div>;
}
